---
language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

addons:
  postgresql: '9.6'

env:
  global:
    - METKA_DB_USER=postgres
    - METKA_DB_NAME=metka

before_script:
  - gem update --system
  - bundle exec rake dummy:db:create
  - RAILS_ENV=test bundle exec rake dummy:db:create dummy:db:migrate