name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: RSpec
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1